version: "3"

services:
  performancetest:
    build: ./
    image: dockerbry/spring-boot-performance:0.0.1-SNAPSHOT

    expose:
      - 8080
      - 5005
    ports:
      - 8081:8080
      - 5005:5005
    environment:
      - SERVER_PORT=8080
      - JVM_OPTS=-Xmx256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=5005 -Dcom.sun.management.jmxremote.port=5005 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

